### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by manuGil** [coderefinery/word-count#12]
The Exercise preparation shows that a `requirements.txt` should be at the root of this repo. Is the file missing? or is it on purpose?

description: https://coderefinery.github.io/reproducible-research/04-workflow-management/#exercise-preparation

**Comment by manuGil** [comment]
I see that #11 calls to use the `environment.yml` instead. This should do it, I think.

**Comment by bast** [comment]
But thanks for pointing it out. Sorry that things are shifting so last minute.
