### ISSUE TITLE
Add requirements.txt for documentation workflow

### ISSUE THREAD

**Issue by rantahar** [coderefinery/word-count#13]
In the documentation 

Creating the Conda environment in a GitHub Action takes a very long time. Runtime is more than 1 hour, compared to a few seconds with pip. Adding a requirements.txt here would make the documentation workflow simpler.

Alternatively, we could add a setup.py, or add the requirements.txt file as an exercise.

The actual requirements for the sphinx build are sphinx and sphinx_rtd_theme, so only those two need to be added.

**Comment by rantahar** [comment]
For now I'm using pip directly to install these two. This might be the best option.
See line 82 in https://github.com/rantahar/documentation/blob/github_pages/content/gh_workflow.md

**Comment by bast** [comment]
Not relevant anymore since documentation lesson does not use this example anymore.
