### ISSUE TITLE
requirements.txt cannot be installed with conda on some OS

### ISSUE THREAD

**Issue by andestro** [coderefinery/word-count#2]
On Ubuntu 18.04.3 LTS, possibly also Windows. 

Running `conda create -c bioconda --name wordcount --file requirements.txt` results in conflicting dependencies. Snakemake seems to be likely culprit, although the base conda environment supports it. 

A manual run `conda install -c bioconda snakemake-minimal` fails even on a fresh conda environment. However, the full snakemake, without version specifier can be installed with `conda install -c bioconda snakemake` as long as numpy and matplotlib are not installed (these can be installed after installation of snakemake. 

A possible workaround is to manually create a fresh conda environment, install the full, version-unspecific snakemake, and **then** install the rest of the requirements.

**Comment by bast** [comment]
Thank you for the description and workaround! This is related to https://github.com/coderefinery/reproducible-research/issues/87.

**Comment by bast** [comment]
It seems we have solved https://github.com/coderefinery/reproducible-research/issues/87.
