### ISSUE TITLE
Better setup for exercise repo

### ISSUE THREAD

**Issue by Sabryr** [coderefinery/word-count#47]
From Chat:
---
what we should do to not accumulate PRs which we do not integrate and to not rewind (dangerous, plus requires permissions), is to create an exercise repo a la git collaborative by git importing a template (which can very well be the word-count)

---
For Tartu I have followed the instructor guide https://coderefinery.github.io/documentation/guide/ and set it up. Yes I agree this procedure is unsustainable, specially in the future plan where CodeRefinery members will involve less and less when presenting material.

**Comment by bast** [comment]
I think one possible path forward is to create a GitHub template.

**Comment by bast** [comment]
Followed up in https://github.com/coderefinery/documentation/issues/105
