### ISSUE TITLE
py2 vs py3 encoding issues have resurfaced

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/word-count#8]
Simply removing the `encoding="utf-8"` option to `open` seemed to solve the python2 vs python3 incompatibility with string formatting (it worked on my (macOS) and Radovan's (nixOS?) laptops). But in a Ubuntu 16.04 Docker container with Python 3.5.2 and 3.6.5 the problem is back:

To reproduce the problem in Ubuntu 16.04:
```
$ python source/wordcount.py data/last.txt processed_data/last.dat
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6862: ordinal not in range(128)
```
- replacing open(filename, "r") with io.open(filename, encoding="utf-8", "r") solves this problem for both python 3.5.2 and 3.6.5
  - but it brings back the problem for python2.7!

**Comment by bast** [comment]
It seems docker uses a different locale. I will try to reproduce this and suggest a PR.

**Comment by bast** [comment]
The worst thing is that I cannot reproduce it locally. But I will try to go for the io solution although I don't like it so much. It is very unfortunate that the example data contains special characters - this is unnecessary complication but I understand that we did not invent it.

**Comment by bast** [comment]
Can we debug it together? I cannot reproduce it even changing locales on my computer.

**Comment by wikfeldt** [comment]
ah yes the locale is very minimal. I've managed to solve this now by adding to the Dockerfile an installation of locales and running of locale-gen

**Comment by wikfeldt** [comment]
Thanks for the effort!
